# Move unused entries from campaigns.yml here

donation_form_design:
  description: Test design changes to donation form
  reference: "https://phabricator.wikimedia.org/T212203"
  start: "2018-12-21 20:00:00"
  end: "2019-01-07 23:00:00"
  active: true
  buckets:
    - default
    - design_change
  default_bucket: default
  url_key: dsn


usability:
  description: Change the user experience on the donation page by removing immediate scrolling, some subheaders and moving newsletter opt-in
  reference: "https://phabricator.wikimedia.org/T202855"
  start: "2018-09-19 14:00:00"
  end: "2018-10-05 14:00:00"
  active: true
  buckets:
    - old
    - improved
  default_bucket: old
  url_key: us

donation_address:
  description: Test address form being required immediately against only being presented optionally on the confirmation page
  reference: "https://phabricator.wikimedia.org/T211666"
  start: "2018-12-12 12:00:00"
  end: "2019-01-07 23:00:00"
  active: true
  buckets:
    - required
    - optional
  default_bucket: required
  url_key: da

anon_form_display:
  description: >
    Test form variations of selecting anonymous donation - with selecting "address type" (a radio group with three choices)
    or 2 groups of radio buttons, first for selecting anonymous yes/no, then address type person/company.
  reference: "https://phabricator.wikimedia.org/T237939"
  start: "2019-11-19 11:00:00"
  end: "2019-12-31 23:00:00"
  buckets:
    - "address_type"
    - "two_steps"
    - "two_steps_fixed_disclaimer"
  default_bucket: "address_type"
  url_key: fd
  active: true
  param_only: true

  membership_incentive:
    description: Test if incentives help drive memberships
    reference: "https://phabricator.wikimedia.org/T270068"
    start: "2020-12-22"
    end: "2021-03-09"
    buckets:
      - "no_incentive"
      - "incentive"
    default_bucket: "no_incentive"
    url_key: incentive
    active: true
    param_only: true

membership_call_to_action:
  description: Display different content for membership call to action on donation confirmation page
  reference: "https://phabricator.wikimedia.org/T210083"
  start: "2018-11-29 19:00:00"
  end: "2019-01-07 23:59:59"
  buckets:
    - "regular"
    - "video"
  default_bucket: "regular"
  url_key: mbcat
  active: true

amount_options:
  description: Test different amount options. First two options are the same because we want to avoid having 0 as a possible value of the URL parameter.
  reference: "https://phabricator.wikimedia.org/T211545"
  start: "2018-12-12 00:00:00"
  end: "2018-12-25 23:59:59"
  buckets:
    - "5to300_0"
    - "5to300"
    - "5to100"
    - "15to250"
    - "30to250"
    - "50to500"
  default_bucket: "5to300"
  url_key: amtopt
  active: true

compact_design:
  description: Test form design variation where the design is more compact by moving elements onto the same row and generally closer together.
  reference: "https://phabricator.wikimedia.org/T236667"
  start: "2019-11-05 14:00:00"
  end: "2019-12-31 23:00:00"
  buckets:
    - "classic"
    - "compact"
  default_bucket: "classic"
  url_key: compact
  active: true
  param_only: true