# Move unused entries from campaigns.yml here

donation_form_design:
  description: Test design changes to donation form
  reference: "https://phabricator.wikimedia.org/T212203"
  start: "2018-12-21 20:00:00"
  end: "2019-01-07 23:00:00"
  active: true
  buckets:
    - default
    - design_change
  default_bucket: default
  url_key: dsn


usability:
  description: Change the user experience on the donation page by removing immediate scrolling, some subheaders and moving newsletter opt-in
  reference: "https://phabricator.wikimedia.org/T202855"
  start: "2018-09-19 14:00:00"
  end: "2018-10-05 14:00:00"
  active: true
  buckets:
    - old
    - improved
  default_bucket: old
  url_key: us

donation_address:
  description: Test address form being required immediately against only being presented optionally on the confirmation page
  reference: "https://phabricator.wikimedia.org/T211666"
  start: "2018-12-12 12:00:00"
  end: "2019-01-07 23:00:00"
  active: true
  buckets:
    - required
    - optional
  default_bucket: required
  url_key: da