# This file is used during unit tests and overrides campaign configurations
#
# Set all campaigns to inactive to force the tests using the default code paths

skins:
  active: false
  buckets:
     - "test"
  default_bucket: "test"

donation_address:
  active: true
