# Configuration file for defining A/B test campaigns
#
# Example
# skins:
#    description: Test different skins
#    reference: "https://phabricator.wikimedia.org/T123"
#    start: "2017-10-01"
#    end: "2019-12-31"
#    buckets:
#        - "10h16"
#        - cat17
#    default_bucket: cat17
#
# Start each campaign with a unique key, that is "campaign name". Then add the following keys:
# description: (optional) What this campaign is about
# reference: (optional) URL where you can read more about it, e.g. Phabricator ticket. You need to enclose the URL in quotes
# start: Start date, in either YYYY-MM-DD or YYYY-MM-DD HH:MM:SS format. If no time is specified, it will be 0:00:00. Timezone is set in app config.
# end: (Optional) End date, in either YYYY-MM-DD or YYYY-MM-DD HH:MM:SS format. If no time is specified, it will be 23:59:59 of that day. Timezone is set in app config.
# active: Date-independent toggle for test
# buckets: List of bucket names
# default_bucket: used bucket when campaign is not active. Must be listed in buckets.
# url_key: URL parameter key used for assigning buckets to people

donation_address:
  description: Test address form being required immediately against only being presented optionally on the confirmation page
  reference: "https://phabricator.wikimedia.org/T196885"
  start: "2018-07-01"
  end: "2018-12-31"
  active: false
  buckets:
    - required
    - optional
  default_bucket: required
  url_key: da


skins:
  description: Test different skins
  reference: "https://phabricator.wikimedia.org/T196335"
  start: "2017-10-01"
  end: "2099-12-31"
  buckets:
    - "cat17"
    - "10h16"
  default_bucket: "cat17"
  url_key: skin
  active: false