# This file is used on test server
#
# Set all campaigns to inactive to force the test server to use the default code paths

skins:
  active: true
  start: "2018-10-10"
  end: "2099-12-31"

membership_call_to_action:
  active: true

amount_options:
  active: true
  start: "2018-12-01"

anon_form_display:
  active: true
  start: "2019-10-01"

compact_design:
  active: true
  start: "2019-10-06 10:00:00"