# This file is meant to be included from the deployment.yml playbook
# It will create an archive of the source code and all its PHP and JavaScript dependencies
#
# The variable "build_dir" contains the inventory-specific path where all the code is checked out and assembled.
# That path could be deleted between deployments, but for performance reasons the code should stay in place.
# "build_dir" is passed in from deployment.yml
#
# All other variables come from the inventory file.

- name: Checkout code
  git: repo=https://github.com/wmde/FundraisingFrontend.git dest={{ build_dir }} version={{ build_branch }} force=yes

- name: Install PHP dependencies
  make:
    chdir: "{{ build_dir }}"
    target: install-php
    params:
      COMPOSER_FLAGS: "--no-dev --prefer-dist --optimize-autoloader --no-progress --no-interaction"
      DOCKER_FLAGS: ""
      BUILD_DIR: "{{ build_dir }}"

- name: Create fake home for npm install as non-root
  file:
    path: "{{ build_dir }}/var/npmbuild"
    state: directory

- name: Install npm packages
  make:
    chdir: "{{ build_dir }}"
    target: install-js
    params:
      TMPDIR: "{{ build_dir }}/var/npmbuild"
      DOCKER_FLAGS: ""
      BUILD_DIR: "{{ build_dir }}"

- name: Compile & copy Javascript to web folder
  make:
    chdir: "{{ build_dir }}"
    target: js
    params:
      BUILD_DIR: "{{ build_dir }}"
      DOCKER_FLAGS: ""

- name: Create tarball
  shell: tar -czf {{ build_dir }}.tar.gz --exclude=".git" --exclude=node_modules --exclude=var -C {{ build_dir }} . warn=no
